<a href="https://colab.research.google.com/github/abd1bayev/Data_screper/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
import numpy as np

In [ ]:
a = ([[1, 2, 3, 4], [0, 1, 1, 1], [7, 7, 7, 7]])
b = np.array(a)
b.dtype

dtype('int64')

NumPy np sifatida
NumPy odatda np taxallus ostida import qilinadi.

taxallus: Pythonda taxalluslar bir xil narsaga murojaat qilish uchun muqobil nomdir.

asImport paytida kalit so'z bilan taxallus yarating :

import numpy as np
npEndi NumPy to'plamini o'rniga deb atash mumkin numpy.



In [ ]:
# Endi NumPy import qilingan va safarga tayyor.
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# npEndi NumPy to'plamini o'rniga deb atash mumkin numpy.
arr = np.array([1, 2, 3, 4, 5])
print(arr)

In [ ]:
# Funktsiyadan foydalanib, biz NumPy ndarrayob'ektini yaratishimiz mumkin array().
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

type(): Ushbu o'rnatilgan Python funktsiyasi bizga unga uzatilgan ob'ekt turini aytadi. Yuqoridagi kodda bo'lgani kabi, arrbu numpy.ndarrayturdagi ekanligini ko'rsatadi.

In [ ]:
# Qiymati 42 bo'lgan 0 o'lchamli massiv yarating
a = np.array(42)
print(a)

In [ ]:
# 1,2,3 va 4,5,6 qiymatlari bo'lgan ikkita massivdan iborat ikki o'lchovli massiv yarating:
arr = np.array([[1,2,3], [4,5,6]])
arr

In [ ]:
# 1,2,3 va 4,5,6 qiymatlari bo‘lgan ikkita massivni o‘z ichiga olgan ikkita 2D massivli 3D massiv yarating:
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

In [ ]:
# Massivlar qancha o'lchamga ega ekanligini tekshiring:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], 4,5,6], [[1,2,3], [4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


In [ ]:
# 5 o'lchovli massiv yarating va uning 5 o'lchovli ekanligini tekshiring:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('olchamlar soni:', arr.ndim)

[[[[[1 2 3 4]]]]]
olchamlar soni: 5


In [ ]:
# NumPy massivini indekslash
# Quyidagi massivdan birinchi elementni oling:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
# Quyidagi massivdan ikkinchi elementni oling.
arr = np.array([1,2,3,4])
print(arr[1])

2


In [ ]:
# Quyidagi massivdan uchinchi va to‘rtinchi elementlarni oling va ularni qo‘shing.
arr = np.array([1, 2, 3, 4, 5])
print(arr[2] + arr[3])

7


In [ ]:
# Birinchi qator, ikkinchi ustundagi elementga kiring:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('1-qatordagi 2-element:', arr[0, 1])

1-qatordagi 2-element: 2


2-D massivlariga kirish
2 oʻlchamli massivlar elementlariga kirish uchun elementning oʻlchami va indeksini ifodalovchi vergul bilan ajratilgan butun sonlardan foydalanishimiz mumkin.

Ikki o'lchovli massivlarni satr va ustunlardan iborat jadval kabi o'ylab ko'ring, bu erda satr o'lchamni va indeks ustunni ifodalaydi.



In [ ]:
# Birinchi massivning ikkinchi massivining uchinchi elementiga kirish:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


3-D massivlariga kirish
3 o'lchamli massivlar elementlariga kirish uchun biz elementning o'lchamlari va indeksini ifodalovchi vergul bilan ajratilgan butun sonlardan foydalanishimiz mumkin.



Misol tushuntirildi
arr[0, 1, 2]qiymatni chop etadi 6.

Va shuning uchun:

Birinchi raqam ikkita massivni o'z ichiga olgan birinchi o'lchamni ifodalaydi:
[[1, 2, 3], [4, 5, 6]]
va:
[[7, 8, 9], [10, 11, 12]]
Chunki ni tanladik 0, bizda birinchi massiv qoldi:
[[1, 2, 3], [4, 5, 6]]

Ikkinchi raqam ikkinchi massivni ifodalaydi, u ham ikkita massivni o'z ichiga oladi:
[1, 2, 3]
va:
[4, 5, 6] ni
tanlaganimiz 1uchun bizda ikkinchi massiv qoladi:
[4, 5, 6]

Uchinchi raqam uchta qiymatni o'z ichiga olgan uchinchi o'lchovni ifodalaydi:
4
5
6
ni tanlaganimiz 2uchun biz uchinchi qiymatga erishamiz:
6

In [ ]:
# Ikkinchi xiralikdan oxirgi elementni chop eting:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2-chi xiralikdagi oxirgi element:', arr[1, -1])

2-chi xiralikdagi oxirgi element: 10


Massivlarni kesish
Pythonda tilimlash bir berilgan indeksdan boshqa indeksga elementlarni olishni anglatadi.

Indeks o'rniga tilimni quyidagicha o'tkazamiz: .[start:end]

Biz qadamni quyidagicha belgilashimiz mumkin: .[start:end:step]

Agar biz o'tmagan bo'lsak, uni 0 deb hisoblaymiz

Agar biz ushbu o'lchamdagi massivning ko'rib chiqilgan uzunligini tugatmasak

Agar biz qadamni o'ta olmasak, u 1 deb hisoblanadi

In [ ]:
# Quyidagi massivdan indeks 1 dan 5 gacha bo'lgan elementlarni ajrating:
a = np.array([1,2,3,4,5,6,7])
print(a[1:5])

Eslatma: Natija boshlang'ich indeksini o'z ichiga oladi , lekin yakuniy indeksni o'z ichiga olmaydi .

In [ ]:
# Elementlarni 4-indeksdan massiv oxirigacha bo'laklarga bo'ling:
a = np.array([1,2,3,4,5,6,7])
print(a[4:])

In [ ]:
# Elementlarni boshidan 4-indeksgacha bo'ling (qo'shilmaydi):
a = np.array([1,2,3,4,5,6,7])
print(a[:4])

Salbiy kesish
Oxirgi indeksga murojaat qilish uchun minus operatoridan foydalaning:

In [ ]:
# Salbiy kesish
# 3-indeksning oxiridan 1-indeksgacha kesing:
a = np.array([1,2,3,4,5,6,7])
print(a[-3:-1])

QADAM
stepKesish bosqichini aniqlash uchun qiymatdan foydalaning :

In [ ]:
# QADAM
# Indeks 1 dan indeks 5 gacha bo'lgan har bir boshqa elementni qaytaring:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

In [ ]:
# Butun massivdan boshqa har bir elementni qaytaring:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

## ***2-D massivlarni kesish***



In [ ]:
# Ikkinchi elementdan 1-indeksdan 4-indeksgacha bo'lgan elementlarni kesib oling (qo'shilmagan):
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


Eslatma: Esda tutingki, ikkinchi element indeks 1 ga ega.

In [ ]:
# Ikkala elementdan indeks 2 ni qaytaring:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


Python-da ma'lumotlar turlari
Odatiy bo'lib Python quyidagi ma'lumotlar turlariga ega:

strings- matn ma'lumotlarini ifodalash uchun ishlatiladi, matn tirnoq ostida beriladi. masalan, "ABCD"
integer- butun sonlarni ifodalash uchun ishlatiladi. masalan -1, -2, -3
float- haqiqiy sonlarni ifodalash uchun ishlatiladi. masalan, 1.2, 42.42
boolean- True yoki False ifodalash uchun ishlatiladi.
complex- kompleks sonlarni ifodalash uchun ishlatiladi. masalan, 1,0 + 2,0j, 1,5 + 2,5j
NumPy-da ma'lumotlar turlari
NumPy-da ba'zi qo'shimcha ma'lumotlar turlari mavjud va bitta belgili ma'lumotlar turlariga murojaat qiling, masalan i, butun sonlar, ubelgisiz tamsayılar va hokazo.

Quyida NumPy-dagi barcha ma'lumotlar turlari va ularni ifodalash uchun ishlatiladigan belgilar ro'yxati keltirilgan.

i- butun son
b- mantiqiy
u- belgisiz butun son
f- suzuvchi
c- murakkab float
m- vaqt deltasi
M- sana vaqti
O- ob'ekt
S- ip
U- unicode string
V- boshqa turdagi xotiraning qattiq qismi (bo'sh)
Massivning ma'lumotlar turini tekshirish
NumPy massivi obyekti massivning dtype ma’lumotlar turini qaytaradigan xususiyatga ega:



In [ ]:
# Massiv ob'ektining ma'lumotlar turini oling:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
# Satrlarni o'z ichiga olgan massivning ma'lumotlar turini oling:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


Biz array()massivlarni yaratish uchun funksiyadan foydalanamiz, bu funksiya ixtiyoriy argumentni olishi mumkin: dtype bu bizga massiv elementlarining kutilayotgan ma’lumotlar turini aniqlash imkonini beradi:

In [ ]:
# Ma'lumotlar turi qatori bilan massiv yarating:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

i, u, uchun fva biz o'lchamni Sham Ubelgilashimiz mumkin.

In [ ]:
import numpy as np

In [ ]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 ==1]

array([1, 3, 5, 7, 9])

In [ ]:
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.arange(12)
arr
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange  